# Dockerfile
FROM python:3.12-slim

# Working directory
WORKDIR /app

# Install GCC compiler
# This is necessary for building some Python packages that require compilation
RUN apt-get update && apt-get install -y gcc

# Copy all files from the current directory to the working directory
COPY . . 

# Install Poetry
RUN pip install poetry==2.1.3

# Install dependencies using Poetry
RUN poetry config virtualenvs.create false && poetry install --only main --no-root

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh


ENTRYPOINT ["/entrypoint.sh"]
CMD ["python", "manage.py", "runserver_plus", "0.0.0.0:8000", "--cert-file", "cert.crt", "--settings=core.settings.prod"]