# Generated by Django 5.2.4 on 2025-11-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('blogs', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, help_text='Posts this reader marked as favorite.', related_name='favorited_by', to='blogs.post'),
        ),
    ]
