# Generated by Django 5.2.4 on 2025-11-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAuthorProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Your Profile',
                'verbose_name_plural': 'Your Profile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.authorprofile',),
        ),
    ]
