# Generated by Django 5.2.4 on 2025-11-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_selfauthorproxy_authorproxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Your Profile',
                'verbose_name_plural': 'Your Profile',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.readerprofile',),
        ),
    ]
