# Generated by Django 5.2.4 on 2025-11-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_readerproxy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorProxy',
        ),
        migrations.DeleteModel(
            name='ReaderProxy',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('reader', 'Reader')], default='reader', help_text="Defines the user's role: Author or Reader.", max_length=20),
        ),
    ]
