# Generated by Django 5.2.4 on 2025-11-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_authorproxy_delete_readerproxy_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
    ]
