# Generated by Django 5.2.4 on 2025-11-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_readerprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='readers/'),
        ),
    ]
