# Generated by Django 5.2.4 on 2025-11-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_readerprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readerprofile',
            name='favorite_posts',
        ),
    ]
